journal_project/urls.py
from django.contrib import admin
from django.urls import path
from journal_app.views import views, entry_views, profile_views, location_views
from django.contrib.auth import views as auth_views
from journal_app.views.entry_views import EntryListCreateView, EntryRetrieveUpdateDestroyView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('add_location/', location_views.add_location, name='add_location'),
    path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('accounts/profile/', profile_views.profile, name='profile'),
    path('entry/add', entry_views.add_entry, name='add_entry'),  # Verwenden Sie entry_views hier
    path('entry/edit/<int:entry_id>/', entry_views.edit_entry, name='edit_entry'),  # ... und hier
    path('entry/delete/<int:entry_id>/', entry_views.delete_entry, name='delete_entry'),  # ... und hier
    path('entry/list', entry_views.list_entries, name='list_entries'),
    # API
    path('api/entry/', EntryListCreateView.as_view(), name='api_entry_list_create'),
    path('api/entry/<int:pk>/', EntryRetrieveUpdateDestroyView.as_view(), name='api_entry_retrieve_update_destroy'),
    path('search_entries/', views.search_entries, name='search_entries'),
]

journal_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from django.core.exceptions import ValidationError
from simple_history.models import HistoricalRecords

class NoAttributSet(ValidationError):
    pass

class TimeFrame(models.Model):
    start_time = models.DateTimeField(null=True, blank=True)
    end_time = models.DateTimeField(null=True, blank=True)
    history = HistoricalRecords()
    
    def clean(self):
        if not self.end_time and not self.start_time:
            raise NoAttributSet(_('Start or end time must be set.'))
        if self.end_time and self.start_time:
            if self.end_time <= self.start_time:
                raise ValidationError(_('End time must be after start time.'))

    def __str__(self):
        return f"{self.start_time} to {self.end_time}"

class Location(models.Model):
    name = models.CharField(max_length=200)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    history = HistoricalRecords()
    
    def clean(self):
        if self.latitude < -90 or self.latitude > 90:
            raise ValidationError(_('Latitude must be between -90 and 90.'))
        if self.longitude < -180 or self.longitude > 180:
            raise ValidationError(_('Longitude must be between -180 and 180.'))

class Entry(models.Model):
    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True)
    parent_entries = models.ManyToManyField('self', blank=True, related_name='child_entries')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    time_frame = models.ForeignKey(TimeFrame, on_delete=models.SET_NULL, null=True, blank=True, related_name='entry')
    history = HistoricalRecords()

    def clean(self):
        if not(self.title or self.description):
            raise ValidationError(_('Title or description must be set.'))
    def __str__(self):
        string = f'Entry #{self.id}: '
        if self.title:
            string += f'{self.title}: '
        if self.description:
            string += f'{self.description}: '
        if self.time_frame:
            if self.time_frame.start_time:
                string += str(self.time_frame.start_time) + ' '
                if self.time_frame.end_time:
                    string += "-"
            if self.time_frame.end_time:
                string += str(self.time_frame.start_time) + ' '
        if string.count('') >= 40:
            string = f'{string[:40]}...'
        return string

journal_app/forms.py
from django import forms
from .models import Entry, Location, TimeFrame

class TimeFrameForm(forms.ModelForm):
    start_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False)
    end_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False)
    
    class Meta:
        model = TimeFrame
        fields = ['start_time', 'end_time']

class EntryForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(), required=False)
    parent_entries = forms.ModelMultipleChoiceField(
        queryset=Entry.objects.all(),
        widget=forms.SelectMultiple(attrs={'hidden': True}),
        required=False
    )
    
    class Meta:
        model = Entry
        fields = ['title', 'description', 'location', 'parent_entries']

class LocationForm(forms.ModelForm):
    latitude = forms.FloatField(widget=forms.NumberInput(attrs={'min': '-90', 'max': '90'}))
    longitude = forms.FloatField(widget=forms.NumberInput(attrs={'min': '-180', 'max': '180'}))
    
    class Meta:
        model = Location
        fields = ['name', 'latitude', 'longitude']
        
class BulkDeleteForm(forms.Form):
    selected_entries = forms.ModelMultipleChoiceField(queryset=Entry.objects.all(), widget=forms.CheckboxSelectMultiple)

class SearchForm(forms.Form):
    title = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Search'}))
    description = forms.CharField(required=False, widget=forms.TextInput(attrs={'placeholder': 'Search'}))
    time_frame__start_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False)
    time_frame__end_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False)
    time_frame__start_time_gte = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False)
    time_frame__end_time_gte = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False)
    time_frame__start_time_lte = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False)
    time_frame__end_time_lte = forms.DateTimeField(widget=forms.DateTimeInput(attrs={'type': 'datetime-local'}), required=False)

journal_app/views/common_views.py
from django.urls import reverse
from django.utils.translation import gettext as _

def getNavigationItems(request):
    nav_items = [
        {'url': reverse('index'), 'label': _('Home')},
        {'url': reverse('list_entries'), 'label': _('Filter Entries')},
    ]

    if request.user.is_authenticated:
        nav_items.extend([
            {'url': reverse('add_location'), 'label': _('Add Location')},
            {'url': reverse('add_entry'), 'label': _('Add Entry')},
            {'url': reverse('logout'), 'label': _('Logout')},
        ])
    else:
        nav_items.append({'url': reverse('login'), 'label': _('Login')})
    return nav_items

journal_app/views/entry_views.py
from django.shortcuts import render, get_object_or_404, redirect
from journal_app.models import Entry, TimeFrame, NoAttributSet
from journal_app.forms import EntryForm, TimeFrameForm, SearchForm, BulkDeleteForm
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext as _
from django.urls import reverse
from django.http import HttpResponseForbidden
from django.contrib.auth.decorators import login_required
from .common_views import getNavigationItems
from rest_framework import generics
from journal_app.serializers import EntrySerializer

class EntryListCreateView(generics.ListCreateAPIView):
    queryset = Entry.objects.all()
    serializer_class = EntrySerializer

class EntryRetrieveUpdateDestroyView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Entry.objects.all()
    serializer_class = EntrySerializer

def list_entries(request):
    search_form = SearchForm(request.GET)
    bulk_delete_form = BulkDeleteForm(request.POST or None)

    if request.method == 'GET' and search_form.is_valid():
        filters = build_filters_from_form(search_form.cleaned_data)
        filtered_entries = Entry.objects.filter(**filters)
    else:
        filtered_entries = Entry.objects.all()

    if request.method == 'POST' and bulk_delete_form.is_valid():
        selected_entries = bulk_delete_form.cleaned_data['selected_entries']
        selected_entries.delete()

    context = {
        'filtered_entries': filtered_entries,
        'bulk_delete_form': bulk_delete_form,
        'search_form': search_form,
        'nav_items': getNavigationItems(request),
    }
    return render(request, 'journal_app/entry/entries_list.html', context)

def build_filters_from_form(cleaned_data):
    filters = {}

    filter_mapping = {
        'title': 'title__icontains',
        'description': 'description__icontains',
        'time_frame__start_time': 'time_frame__start_time',
        'time_frame__end_time': 'time_frame__end_time',
        'time_frame__start_time_gte': 'time_frame__start_time__gte',
        'time_frame__end_time_gte': 'time_frame__end_time__gte',
        'time_frame__start_time_lte': 'time_frame__start_time__lte',
        'time_frame__end_time_lte': 'time_frame__end_time__lte',
    }

    for field_name, filter_key in filter_mapping.items():
        field_value = cleaned_data.get(field_name)
        if field_value:
            filters[filter_key] = field_value

    return filters

@login_required
def edit_entry(request, entry_id):
    entry = get_object_or_404(Entry, id=entry_id)
    if entry.user != request.user:
        return HttpResponseForbidden(_("The user needs to own the page to edit it"))

    if request.method == 'POST':
        entry_form = EntryForm(request.POST, instance=entry)
        if entry_form.is_valid():
            entry_form.save()
    else:
        entry_form = EntryForm(instance=entry)

    return render(request, 'journal_app/entry/edit_entry.html', {'entry_form': entry_form, 'time_frame_form': TimeFrameForm(instance=entry.time_frame), 'entry': entry, 'nav_items': getNavigationItems(request)})

@login_required
def add_entry(request): 
    time_frame_form = TimeFrameForm(None)
    entry_form = EntryForm(None)
    status_code = 200
    if request.method == "POST":
        entry_form = EntryForm(request.POST)
        if ('end_time' in request.POST and request.POST['end_time']) or ('start_time' in request.POST and request.POST['start_time']):
            time_frame_form = TimeFrameForm(request.POST)
        time_frame = None
        try:
            if time_frame_form.is_valid():
                 # Save the TimeFrame instance but don't commit to the database yet
                time_frame = time_frame_form.save()
        except NoAttributSet:
            time_frame_form = TimeFrameForm(None)
        
        if entry_form.is_valid():
            
            # Save the Entry instance but don't commit to the database yet
            entry = entry_form.save(commit=False)
            
            if time_frame:
                # Associate the TimeFrame with the Entry
                entry.time_frame = time_frame
                
                # Save the TimeFrame to the database
                time_frame.save()
            
            # Set the user for the Entry
            entry.user = request.user
            
            # Save the Entry to the database
            entry.save()
            
            
            # Save many-to-many data if needed
            entry_form.save_m2m()
            
            # Redirect 
            return redirect('edit_entry', entry_id=entry.id)
        else:
            status_code=400
    return render(request, 'journal_app/entry/add_entry.html', {'entry_form': entry_form, 'time_frame_form': time_frame_form, 'nav_items': getNavigationItems(request)},status=status_code)

@login_required
def delete_entry(request, entry_id):
    entry = get_object_or_404(Entry, id=entry_id)
    
    # Überprüfen Sie, ob der Benutzer der Eigentümer des Eintrags ist
    if entry.user != request.user:
        return HttpResponseForbidden("Sie haben keine Berechtigung, diesen Eintrag zu löschen.")

    if request.method == 'POST':
        entry.delete()
        return redirect('index')  # Nach der Löschung zur Indexseite umleiten

    return render(request, 'journal_app/entry/delete_entry.html', {'entry': entry, 'nav_items': getNavigationItems(request)})

journal_app/views/init.py
from .location_views import AddLocation
from .entry_views import AddEntry, EditEntry, DeleteEntry, FilterEntries
from .profile_views import ProfileView

journal_app/views/location_views.py
from django.contrib.auth.decorators import login_required
from ..forms import LocationForm
from ..models import Location
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import gettext as _
from .common_views import getNavigationItems

@login_required
def add_location(request):
    if request.method == 'POST':
        form = LocationForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = LocationForm()

    locations = Location.objects.all()
    return render(request, 'journal_app/add_location.html', {'form': form, 'locations': locations, 'nav_items': getNavigationItems(request)})

journal_app/views/profile_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import gettext as _
from .common_views import getNavigationItems

@login_required
def profile(request):
    return render(request, 'journal_app/profile.html')

journal_app/views/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import gettext as _
from django.urls import reverse
from django.db.models import Q
from django.utils import timezone
from datetime import datetime
from .common_views import getNavigationItems
from journal_app.models import Entry


def index(request):
    return render(request, 'journal_app/index.html', { 'nav_items': getNavigationItems(request)})

from django.http import JsonResponse

def search_entries(request):
    query = request.GET.get('query')
    entries = Entry.objects.filter(title__icontains=query)[:5]  # Nehmen wir nur die ersten 5 Ergebnisse an
    results = [{"id": entry.id, "title": entry.title} for entry in entries]
    return JsonResponse(results, safe=False)

journal_app/templates/journal_app/entry/add_entry.html
{% extends "base.html" %}
{% block content %}

<h1 class="mb-4">Add</h1>
{% include "journal_app/entry/entry.html" with entry_form=entry_form time_frame_form=time_frame_form%}

{% endblock %}

journal_app/templates/journal_app/entry/delete_entry.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<div class="container">
    <h1 class="mt-5 mb-4">{% trans "Delete Entry" %}</h1>

    <div class="alert alert-warning">
        {% blocktrans %}
            Are you sure you want to delete the entry
        {% endblocktrans %}
        <strong><a href="{% url 'edit_entry' entry.id %}">{{ entry }}</a></strong>?
    </div>

    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <button type="submit" class="btn btn-danger btn-block">{% trans "Delete" %}</button>
            </div>
            <div class="col-md-6">
                <a href="{% url 'index' %}" class="btn btn-success btn-block">{% trans "Cancel" %}</a>
            </div>
        </div>
    </form>
</div>
{% endblock %}

journal_app/templates/journal_app/entry/edit_entry.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
<h1 class="mb-4">{% trans "Edit" %} {{ entry }}</h1>
{% include "journal_app/entry/entry.html" with entry_form=entry_form time_frame_form=time_frame_form %}
<a href="{% url 'delete_entry' entry.id %}" class="btn btn-danger">{% blocktrans %}Delete entry{% endblocktrans %}</a>
{% endblock %}

journal_app/templates/journal_app/entry/entries_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="container">
    <h1>{% trans "Filter Entries" %}</h1>
    <form method="get" action="{% url 'list_entries' %}" class="mb-4">
        {% for field in search_form %}
            <p>
                {{ field.label_tag }} {{ field }}
                <button type="button" class="btn btn-danger btn-sm clear-field" data-field-id="{{ field.auto_id }}">X</button>
                <button type="submit" class="btn btn-primary btn-sm"><i class="fas fa-sync-alt"></i></button>
            </p>
        {% endfor %}
    </form>
    <h2>{% trans "Filtered Entries" %}</h2>
    <form method="post">
        {% csrf_token %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th><input type="checkbox" id="select_all"></th>
                    <th>{% trans "Title" %}</th>
                    <th>{% trans "Description" %}</th>
                    <th>{% trans "Location" %}</th>
                    <th>{% trans "Start Time" %}</th>
                    <th>{% trans "End Time" %}</th>
                    <th>{% trans "Actions" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for entry in filtered_entries %}
                    <tr>
                        <td><input type="checkbox" name="selected_entries" value="{{ entry.id }}"></td>
                        <td>{{ entry.title|truncatechars:50 }}</td>
                        <td data-toggle="tooltip" data-placement="bottom" title="{{ entry.description }}">{{ entry.description|truncatechars:50 }}</td>
                        <td>{{ entry.location }}</td>
                        <td>{{ entry.time_frame.start_time }}</td>
                        <td>{{ entry.time_frame.end_time }}</td>
                        <td>
                            <a href="{% url 'edit_entry' entry.id %}" class="btn btn-primary btn-sm">{% trans "Edit" %}</a>
                            <a href="{% url 'delete_entry' entry.id %}" class="btn btn-danger btn-sm">{% trans "Delete" %}</a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="7">{% trans "No entries found." %}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <input type="submit" value="Delete Selected Entries">
    </form>
    <script>
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip();
            $('#select_all').click(function() {
                $('input[type="checkbox"]').prop('checked', this.checked);
            });
            
            // Clear the content of the associated field when the delete button is clicked and submit the form
            $('.clear-field').click(function() {
                var fieldId = $(this).data('field-id');
                $('#' + fieldId).val('');
                $(this).closest('form').submit();  // Submit the form after clearing the field
            });
        });
    </script>
</div>
{% endblock %}

journal_app/templates/journal_app/entry/entry.html
{% include "errors.html" with form=time_frame_form form_name="TimeFrame" %}
{% include "errors.html" with form=entry_form form_name="Entry" %}
{% load widget_tweaks %}
{% load custom_tags %}
<form method="POST" class="needs-validation" novalidate>
    {% csrf_token %}

<!-- Render Entry Form Fields -->
{% for field in entry_form %}
    <div class="form-group" {% if field|has_hidden_attr %}style="display: none;"{% endif %}>
        {% if not field|has_hidden_attr %}
            {{ field.label_tag }}
        {% endif %}
        {{ field|add_class:"form-control" }}
        {% if field.errors %}
            <span class="text-danger">{{ field.errors }}</span>
        {% endif %}
    </div>
{% endfor %}



    <!-- Render TimeFrame Form Fields -->
    <div class="form-row">
        {% for field in time_frame_form %}
            <div class="form-group col-md-6">
                {{ field.label_tag }}
                {{ field|add_class:"form-control" }}
                {% if field.errors %}
                    <span class="text-danger">{{ field.errors }}</span>
                {% endif %}
            </div>
        {% endfor %}
    </div>

    <div class="form-group">
        <input type="text" id="parent-search" placeholder="Eltern suchen..." class="form-control">
    </div>

    <div id="selected-parents" class="mb-3"></div>

<script>
    $(document).ready(function() {
        const $selectField = $('#id_parent_entries');
        const $container = $('#selected-parents');
    
        function createButton(text, id, btnClass, entry) {
            const $btn = $('<span/>', {
                text: text,
                id: `btn-${id}`,
                class: `btn btn-primary ${btnClass}`
            });
    
            $btn.on('click', function() {
                toggleButton($btn, entry || { id: id, title: text });
            });
    
            return $btn;
        }
    
        function createActiveButtonsForSelectedOptions() {
            $selectField.find('option:selected').each(function() {
                const $btn = createButton($(this).text(), $(this).val(), 'active');
                $container.append($btn);
            });
        }
    
        function toggleButton($btn, entry) {
            if ($btn.hasClass('inactive')) {
                $btn.removeClass('inactive').addClass('active');
    
                const $option = $('<option/>', {
                    value: entry.id,
                    text: entry.title,
                    selected: true
                });
                $selectField.append($option);
            } else {
                $btn.removeClass('active').addClass('inactive');
                $selectField.find(`option[value="${entry.id}"]`).remove();
            }
        }
    
        $('#parent-search').on('input', function() {
            let query = $(this).val();
    
            $.getJSON(`/search_entries/?query=${query}`, function(entries) {
                $container.find('.inactive').remove();
    
                $.each(entries, function(_, entry) {
                    if (!$(`#btn-${entry.id}`).length) {
                        const $btn = createButton(entry.title, entry.id, 'inactive', entry);
                        $container.append($btn);
                    }
                });
            });
        });
    
        createActiveButtonsForSelectedOptions();
    });
    
</script>

<style>
    .inactive {
        background-color: #e0e0e0;
    }

    .active {
        background-color: green;
        color: white;
    }
</style>



    <button type="submit" class="btn btn-primary">Submit</button>
</form>